{
  "openapi": "3.0.0",
  "info": {
    "title": "Books API",
    "version": "1.0.0",
    "description": "A simple API for working with books"
  },
  "servers": [
    {
      "url": "/",
      "description": "Current server"
    }
  ],
  "paths": {
    "/books": {
      "get": {
        "summary": "Get all books",
        "tags": [
          "Books"
        ],
        "responses": {
          "200": {
            "description": "A list of books",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "example": [
                  {
                    "id": "b1",
                    "authorId": "a1",
                    "title": 1984,
                    "publicationDate": "1948-06-08"
                  },
                  {
                    "id": "b2",
                    "authorId": "a2",
                    "title": "Harry Potter and the Philosopher's Stone",
                    "publicationDate": "1997-06-26"
                  },
                  {
                    "id": "b3",
                    "authorId": "a3",
                    "title": "The Hobbit",
                    "publicationDate": "1937-09-21"
                  }
                ]
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Unable to retrieve books"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a new book",
        "tags": [
          "Books"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "id",
                  "authorId",
                  "title",
                  "publicationDate"
                ],
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "The ID of the book"
                  },
                  "authorId": {
                    "type": "string",
                    "description": "The ID of the author"
                  },
                  "title": {
                    "type": "string",
                    "description": "The title of the book"
                  },
                  "publicationDate": {
                    "type": "string",
                    "format": "date",
                    "description": "The publication date of the book"
                  }
                },
                "example": {
                  "id": "b3",
                  "authorId": "a3",
                  "title": "The Hobbit",
                  "publicationDate": "1937-09-21"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "The created book",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": "b3",
                  "authorId": "a3",
                  "title": "The Hobbit",
                  "publicationDate": "1937-09-21"
                }
              }
            }
          }
        }
      }
    },
    "/books/{id}": {
      "get": {
        "summary": "Get a book by ID",
        "tags": [
          "Books"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "description": "The ID of the book to retrieve",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The requested book",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": "b3",
                  "authorId": "a3",
                  "title": "The Hobbit",
                  "publicationDate": "1937-09-21"
                }
              }
            }
          },
          "404": {
            "description": "Book not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Book not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Unable to retrieve book"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update an existing book",
        "tags": [
          "Books"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "description": "The ID of the book to update",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "title",
                  "authorId",
                  "publicationDate"
                ],
                "properties": {
                  "authorId": {
                    "type": "string",
                    "description": "The ID of the author"
                  },
                  "title": {
                    "type": "string",
                    "description": "The title of the book"
                  },
                  "publicationDate": {
                    "type": "string",
                    "format": "date",
                    "description": "The publication date of the book"
                  }
                },
                "example": {
                  "authorId": "a3",
                  "title": "The Hobbit",
                  "publicationDate": "1937-09-21"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The updated book",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "authorId": {
                      "type": "string"
                    },
                    "title": {
                      "type": "string"
                    },
                    "publicationDate": {
                      "type": "string",
                      "format": "date"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete an existing book",
        "tags": [
          "Books"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "description": "The ID of the book to delete",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "No content"
          },
          "404": {
            "description": "Book not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Book not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Unable to delete book"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/authors": {
      "get": {
        "summary": "Get all authors",
        "tags": [
          "Authors"
        ],
        "responses": {
          "200": {
            "description": "A list of authors",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "example": [
                  {
                    "id": "a1",
                    "firstName": "George",
                    "lastName": "Orwell",
                    "birthYear": 1903
                  },
                  {
                    "id": "a2",
                    "firstName": "J.K.",
                    "lastName": "Rowling",
                    "birthYear": 1965
                  },
                  {
                    "id": "a3",
                    "firstName": "J.R.R.",
                    "lastName": "Tolkien",
                    "birthYear": 1892
                  }
                ]
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Unable to retrieve authors"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create a new author",
        "tags": [
          "Authors"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "id",
                  "firstName",
                  "lastName",
                  "birthYear"
                ],
                "properties": {
                  "id": {
                    "type": "string",
                    "description": "The unique identifier for the author"
                  },
                  "firstName": {
                    "type": "string",
                    "description": "The author's first name"
                  },
                  "lastName": {
                    "type": "string",
                    "description": "The author's last name"
                  },
                  "birthYear": {
                    "type": "integer",
                    "description": "The author's birth year"
                  }
                },
                "example": {
                  "id": "a4",
                  "firstName": "Stephen",
                  "lastName": "King",
                  "birthYear": 1947
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "The created author",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": "a4",
                  "firstName": "Stephen",
                  "lastName": "King",
                  "birthYear": 1947
                }
              }
            }
          },
          "400": {
            "description": "Missing required field or duplicate author ID",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Missing required fields. id, firstName, lastName, and birthYear are required."
                    }
                  }
                },
                "examples": {
                  "missingField": {
                    "summary": "Missing required field",
                    "value": {
                      "error": "Missing required fields. id, firstName, lastName, and birthYear are required."
                    }
                  },
                  "duplicateId": {
                    "summary": "Duplicate author ID",
                    "value": {
                      "error": "Author with this ID already exists."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Unable to create author"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/authors/{id}": {
      "get": {
        "summary": "Get an author by ID",
        "tags": [
          "Authors"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "description": "The ID of the author to retrieve",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The requested author",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": "a1",
                  "firstName": "George",
                  "lastName": "Orwell",
                  "birthYear": 1903
                }
              }
            }
          },
          "404": {
            "description": "Author not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Author not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Unable to retrieve author"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update an existing author",
        "tags": [
          "Authors"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The unique identifier for the author"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "firstName",
                  "lastName",
                  "birthYear"
                ],
                "properties": {
                  "firstName": {
                    "type": "string",
                    "description": "The author's updated first name"
                  },
                  "lastName": {
                    "type": "string",
                    "description": "The author's updated last name"
                  },
                  "birthYear": {
                    "type": "integer",
                    "description": "The author's updated birth year"
                  }
                },
                "example": {
                  "firstName": "Updated First Name",
                  "lastName": "Updated Last Name",
                  "birthYear": 1947
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The updated author",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "id": "a4",
                  "firstName": "Updated First Name",
                  "lastName": "Updated Last Name",
                  "birthYear": 1947
                }
              }
            }
          },
          "400": {
            "description": "Missing required field",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Missing required fields. firstName, lastName, and birthYear are required."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Author not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Author not found"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Unable to update author"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete an existing author",
        "tags": [
          "Authors"
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "description": "The ID of the author to delete",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Author successfully deleted"
          },
          "404": {
            "description": "Author not found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Author not found."
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Author cannot be deleted because the author still has books",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Author cannot be deleted because the author still has books."
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal server error",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "type": "string",
                      "example": "Unable to delete author."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {},
  "tags": []
}